const os = require('node:os')

console.log('Operating System Information')
console.log('____________________________')
console.log('\nUser info:', os.userInfo())
console.log('\nHost name:', os.hostname())
console.log('\nHome dir:', os.homedir())
console.log('\nTmp dir:', os.tmpdir())
console.log('\nType:', os.type())
console.log('\nPlatform:', os.platform())
console.log('\nRelease:', os.release())
console.log('\nVersion:', os.version())
console.log('\nArch:', os.arch())
console.log('\nMachine:', os.machine())
console.log('\nEndianness:', os.endianness())
console.log('\nUptime:', os.uptime() / 60 / 60, 'hours')
console.log('\nTotal memory:', os.totalmem() / 1024 / 1024 / 1024, 'gigabytes')
console.log('\nFree memory:', os.freemem() / 1024 / 1024 / 1024, 'gigabytes')
console.log('\nLoadavg:', os.loadavg())
console.log('\nAvailable parallelism:', os.availableParallelism())
console.log('\nCPUs:', os.cpus())
console.log('\nNetwork interfaces:', os.networkInterfaces())
