version: '3'
 
services:
  mysqldb:
    image: mysql:8.3.0
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: your_user_name
      MYSQL_PASSWORD: your_user_password
    ports:
      - "3306:3306"
    volumes:
      - $HOME/volumes_docker/var_lib_mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmincontainer
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8000:80
